version: '3'
services:
    postgres:
        image: timescale/timescaledb:latest-pg10
        container_name: postgres
        restart: always
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASS}
        volumes:
            - ./postgres-data-current:/var/lib/postgresql/data
        networks:
            - postgres
        expose:
            - 5432
    migrate:
        build: ./migrate/
        container_name: migrate
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASS}
            DB_VERSION: ${DB_VERSION}
        volumes:
            - ./migrate/:/root/
        depends_on:
            - postgres
        networks:
            - postgres
networks:
    postgres: