version: '2'
services:
    artemis:
        build: ./backend/
        environment:
            RABBITMQ_HOST: rabbitmq
            MEMCACHED_HOST: memcached
            POSTGRES_HOST: postgres
            SYSLOG_HOST: "syslog:514"
        depends_on:
            - rabbitmq
            - memcached
            - postgres
            - syslog
        volumes:
            - ./backend/:/root/
        networks:
            - rabbitmq
            - memcached
            - postgres
            - syslog
    # grafana:
    #     image: grafana/grafana
    #     restart: always
    #     ports:
    #         - 8001:3000
    #     networks:
    #         - rabbitmq
    #         - postgres
    artemis_webapp:
        build: ./frontend/
        environment:
            RABBITMQ_HOST: rabbitmq
            POSTGRES_HOST: postgres
            SYSLOG_HOST: "syslog:514"
        expose:
            - 8000
        ports:
            - "8000:8000"
        volumes:
            - ./frontend/:/root/
        depends_on:
            - rabbitmq
            - postgres
            - postgrest
            - syslog
        networks:
            - rabbitmq
            - postgres
            - postgrest
            - syslog
    syslog:
        image: "mumblepins/syslog-ng-alpine"
        restart: always
        networks:
            - syslog
    rabbitmq:
        image: "rabbitmq:3-alpine"
        restart: always
        networks:
            - rabbitmq
        expose:
            - 5672
    memcached:
        image: "memcached:alpine"
        restart: always
        networks:
            - memcached
        expose:
            - 11211
    postgres:
        image: "postgres:alpine"
        restart: always
        environment:
            POSTGRES_DB: artemis_db
            POSTGRES_USER: artemis_user
            POSTGRES_PASSWORD: Art3m1s
        networks:
            - postgres
        expose:
            - 5432
    postgrest:
        image: "postgrest/postgrest"
        restart: always
        expose:
            - 3000
        ports:
            - "3000:3000"
        networks:
            - postgres
            - postgrest
        depends_on:
            - postgres
        environment:
            PGRST_DB_URI: postgres://artemis_user:Art3m1s@postgres:5432/artemis_db
            PGRST_DB_SCHEMA: public
            PGRST_DB_ANON_ROLE: artemis_user

networks:
    syslog:
    rabbitmq:
    memcached:
    postgres:
    postgrest:
