version: '3'
services:
    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: pgadmin
        restart: always
        depends_on:
            - postgres
        networks:
            - artemis
        ports:
            - "5050:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGA_USER}
            PGADMIN_DEFAULT_PASSWORD: ${PGA_PASS}
