version: '2'
services:
    graphql:
        image: hasura/graphql-engine:latest
        container_name: graphql
        restart: always
        depends_on:
            - postgres
        networks:
            - artemis
        expose:
            - 8080
        environment:
            HASURA_GRAPHQL_DATABASE_URL: postgres://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}
            HASURA_GRAPHQL_ACCESS_KEY: ${HASURA_SECRET_KEY}
        command:
            - graphql-engine
            - serve
            - --enable-console
