version: '3'
services:
    exabgp:
        container_name: exabgp
         image: mavromat/exabgp-monitor:latest
         restart: always
         networks:
             - artemis
         volumes:
             - ./backend/configs/exabgp.conf:/home/config/exabgp.conf
