version: '3'
services:
    pgtuner:
        image: jfcoz/postgresqltuner
        container_name: pgtuner
        restart: always
        depends_on:
            - postgres
        networks:
            - artemis
        environment:
            PGHOST: ${DB_HOST}
            PGPORT: ${DB_PORT}
            PGDATABASE: ${DB_NAME}
            PGUSERNAME: ${DB_USER}
            PGPASS: ${DB_PASS}
