apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: postgrest
    labels:
      io.kompose.service: postgrest
  spec:
    ports:
    - port: 3000
    selector:
      io.kompose.service: postgrest
- apiVersion: v1
  kind: Service
  metadata:
    name: postgres
    labels:
      io.kompose.service: postgres
  spec:
    ports:
    - port: 5432
    selector:
      io.kompose.service: postgres
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -o deploy.yaml
      kompose.version: 1.16.0 (0c01309)
    creationTimestamp: null
    labels:
      io.kompose.service: artemis
    name: artemis
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: artemis
      spec:
        containers:
        - env:
          - name: MEMCACHED_HOST
            value: memcached
          - name: POSTGRES_HOST
            value: postgres
          - name: RABBITMQ_HOST
            value: rabbitmq
          - name: SYSLOG_HOST
            value: syslog:514
          image: mavromat/artemis
          name: artemis
          imagePullPolicy: Never
          resources: {}
        restartPolicy: Always
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -o deploy.yaml
      kompose.version: 1.16.0 (0c01309)
    creationTimestamp: null
    labels:
      io.kompose.service: memcached
    name: memcached
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: memcached
      spec:
        containers:
        - image: memcached:alpine
          name: memcached
          resources: {}
        restartPolicy: Always
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -o deploy.yaml
      kompose.version: 1.16.0 (0c01309)
    creationTimestamp: null
    labels:
      io.kompose.service: postgres
    name: postgres
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: postgres
      spec:
        containers:
        - env:
          - name: POSTGRES_DB
            value: artemis_db
          - name: POSTGRES_PASSWORD
            value: Art3m1s
          - name: POSTGRES_USER
            value: artemis_user
          image: postgres:alpine
          name: postgres
          resources: {}
        restartPolicy: Always
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -o deploy.yaml
      kompose.version: 1.16.0 (0c01309)
    creationTimestamp: null
    labels:
      io.kompose.service: postgrest
    name: postgrest
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: postgrest
      spec:
        containers:
        - env:
          - name: PGRST_DB_ANON_ROLE
            value: artemis_user
          - name: PGRST_DB_SCHEMA
            value: public
          - name: PGRST_DB_URI
            value: postgres://artemis_user:Art3m1s@postgres:5432/artemis_db
          image: postgrest/postgrest
          name: postgrest
          resources: {}
        restartPolicy: Always
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -o deploy.yaml
      kompose.version: 1.16.0 (0c01309)
    creationTimestamp: null
    labels:
      io.kompose.service: rabbitmq
    name: rabbitmq
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: rabbitmq
      spec:
        containers:
        - image: rabbitmq:3-alpine
          name: rabbitmq
          resources: {}
        restartPolicy: Always
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -o deploy.yaml
      kompose.version: 1.16.0 (0c01309)
    creationTimestamp: null
    labels:
      io.kompose.service: syslog
    name: syslog
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: syslog
      spec:
        containers:
        - image: mumblepins/syslog-ng-alpine
          name: syslog
          resources: {}
        restartPolicy: Always
  status: {}
kind: List
metadata: {}

