apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: postgrest
    labels:
      io.kompose.service: postgrest
  spec:
    ports:
    - port: 3000
    selector:
      io.kompose.service: postgrest
- apiVersion: v1
  kind: Service
  metadata:
    name: postgres
    labels:
      io.kompose.service: postgres
  spec:
    ports:
    - port: 5432
    selector:
      io.kompose.service: postgres
- apiVersion: v1
  kind: Service
  metadata:
    name: syslog
    labels:
      io.kompose.service: syslog
  spec:
    ports:
    - port: 514
    selector:
      io.kompose.service: syslog
- apiVersion: v1
  kind: Service
  metadata:
    name: memcached
    labels:
      io.kompose.service: memcached
  spec:
    ports:
    - port: 11211
    selector:
      io.kompose.service: memcached
- apiVersion: v1
  kind: Service
  metadata:
    name: rabbitmq
    labels:
      io.kompose.service: rabbitmq
  spec:
    ports:
    - port: 5672
    selector:
      io.kompose.service: rabbitmq
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -o deploy.yaml
      kompose.version: 1.16.0 (0c01309)
    creationTimestamp: null
    labels:
      io.kompose.service: artemis
    name: artemis
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: artemis
      spec:
        containers:
        - env:
          - name: MEMCACHED_HOST
            value: memcached
          - name: POSTGRES_HOST
            value: postgres
          - name: RABBITMQ_HOST
            value: rabbitmq
          - name: SYSLOG_HOST
            value: syslog:514
          image: mavromat/artemis
          name: artemis
          imagePullPolicy: Never
          volumeMounts:
          - mountPath: /root/configs/
            name: config-volume
          resources: {}
        restartPolicy: Always
        volumes:
        - name: config-volume
          configMap:
            name: artemis-config
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -o deploy.yaml
      kompose.version: 1.16.0 (0c01309)
    creationTimestamp: null
    labels:
      io.kompose.service: memcached
    name: memcached
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: memcached
      spec:
        containers:
        - image: memcached:alpine
          name: memcached
          resources: {}
        restartPolicy: Always
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -o deploy.yaml
      kompose.version: 1.16.0 (0c01309)
    creationTimestamp: null
    labels:
      io.kompose.service: postgres
    name: postgres
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: postgres
      spec:
        containers:
        - env:
          - name: POSTGRES_DB
            value: artemis_db
          - name: POSTGRES_PASSWORD
            value: Art3m1s
          - name: POSTGRES_USER
            value: artemis_user
          image: postgres:alpine
          name: postgres
          resources: {}
        restartPolicy: Always
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -o deploy.yaml
      kompose.version: 1.16.0 (0c01309)
    creationTimestamp: null
    labels:
      io.kompose.service: postgrest
    name: postgrest
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: postgrest
      spec:
        containers:
        - env:
          - name: PGRST_DB_ANON_ROLE
            value: artemis_user
          - name: PGRST_DB_SCHEMA
            value: public
          - name: PGRST_DB_URI
            value: postgres://artemis_user:Art3m1s@postgres:5432/artemis_db
          image: postgrest/postgrest
          name: postgrest
          resources: {}
        restartPolicy: Always
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -o deploy.yaml
      kompose.version: 1.16.0 (0c01309)
    creationTimestamp: null
    labels:
      io.kompose.service: rabbitmq
    name: rabbitmq
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: rabbitmq
      spec:
        containers:
        - image: rabbitmq:3-alpine
          name: rabbitmq
          resources: {}
        restartPolicy: Always
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -o deploy.yaml
      kompose.version: 1.16.0 (0c01309)
    creationTimestamp: null
    labels:
      io.kompose.service: syslog
    name: syslog
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: syslog
      spec:
        containers:
        - image: mumblepins/syslog-ng-alpine
          name: syslog
          resources: {}
        restartPolicy: Always
  status: {}
- apiVersion: v1
  data:
    config.yaml: |
      #
      # ARTEMIS Configuration File
      #

      # Start of Prefix Definitions
      prefixes:
          forth_prefix_main: &forth_prefix_main
              - 139.91.0.0/16
              # - 139.0.0.0/8
              # [0.0.0.0/0]
              # [0.0.0.0/0, '::/0']
          forth_prefix_lamda: &forth_prefix_lamda
              139.91.250.0/24
          forth_prefix_vod: &forth_prefix_vod
              139.91.2.0/24
      # End of Prefix Definitions

      # Start of Monitor Definitions
      monitors:
          riperis: ['']
          # bgpstreamlive:
          # - routeviews
          # - ris
          # exabgp:
          # - ip: 192.168.1.1
          #   port: 5000
          # - ip: 192.168.5.1
          #   port: 5000
          # bgpstreamhist: /home/vkotronis/Desktop/git_projects/artemis-tool/other/bgpstreamhist/test_dir2
      # End of Monitor Definitions

      # Start of ASN Definitions
      asns:
          forth_asn: &forth_asn
              8522
          grnet_forth_upstream: &grnet_forth_upstream
              5408
          lamda_forth_upstream_back: &lamda_forth_upstream_back
              56910
          vodafone_forth_upstream_back: &vodafone_forth_upstream_back
              12361
      # End of ASN Definitions

      # Start of Rule Definitions
      rules:
      - prefixes:
        - *forth_prefix_main
        origin_asns:
        - *forth_asn
        neighbors:
        - *grnet_forth_upstream
        - *vodafone_forth_upstream_back
        mitigation:
            manual
      - prefixes:
        - *forth_prefix_lamda
        origin_asns:
        - *forth_asn
        neighbors:
        - *lamda_forth_upstream_back
        mitigation:
            manual
      - prefixes:
        - *forth_prefix_vod
        origin_asns:
        - *forth_asn
        neighbors:
        - *vodafone_forth_upstream_back
        mitigation:
            manual
      # End of Rule Definitions
  kind: ConfigMap
  metadata:
    creationTimestamp: 2018-09-28T22:31:18Z
    name: artemis-config
    namespace: default
    resourceVersion: "826"
    selfLink: /api/v1/namespaces/default/configmaps/artemis-config
    uid: 37eaa0f4-c36e-11e8-9f12-0800276622b6
kind: List
metadata: {}

