{{- range .Values.services }}
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: {{ . }}
  name: {{ . }}
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    io.kompose.service: {{ . }}
status:
  loadBalancer: {}
---
{{- end }}
